@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzgzODgzNTM2LCJleHAiOjE3ODM5MTIzMzZ9.Fgvo5FLZ3CNxrRE0MYAuUm5Jls9arYgQEv_uKcOfWok

### Criar produto
POST http://localhost:3000/api/produtos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "codigo": "NB-DELL-01",
  "nome": "Notebook Dell",
  "descricao": "Notebook i5 16GB RAM",
  "altura": 2,
  "largura": 3,
  "comprimento": 2,
  "ativo": true
}

### Buscar todos
GET http://localhost:3000/api/produtos
Authorization: Bearer {{token}}

### Buscar por id
GET http://localhost:3000/api/produtos/1
Authorization: Bearer {{token}}

### Atualizar
PUT http://localhost:3000/api/produtos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Notebook Dell Inspiron",
  "descricao": "Notebook i5 16GB RAM 512GB SSD",
  "altura": 0.2,
  "largura": 0.3,
  "comprimento": 0.2
}

### Ativar/desativar
PATCH http://localhost:3000/api/produtos/1/toggle-ativo
Authorization: Bearer {{token}}

### Deletar
DELETE http://localhost:3000/api/produtos/1
Authorization: Bearer {{token}}